# Plantilla generada por Wallust para Dunst

[urgency_low]
    # El equivalente Hexadecimal a rgba(20, 20, 20, 0.9) es #141414E6
    background = "#141414E6"
    foreground = "#FEFAF3"
    frame_color = "#ACA7A1"

[urgency_normal]
    background = "#141414E6"
    foreground = "#FEFAF3"
    # Puedes usar color2 o color1 dependiendo de qué borde prefieras
    frame_color = "#355D6A" 

[urgency_critical]
    background = "#141414E6"
    foreground = "#FEFAF3"
    # En tu SwayNC usabas @color1 para críticas
    frame_color = "#754D43"