# ==========================================
# 1. FUENTES (Usa la misma que Waybar)
# ==========================================
font_family      JetBrainsMono Nerd Font
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size        12.0

# ==========================================
# 2. VENTANA Y APARIENCIA
# ==========================================
window_padding_width 15
background_opacity 0.7
hide_window_decorations yes
confirm_os_window_close 0

# ==========================================
# 3. CURSOR Y FONDO (Estático)
# ==========================================
cursor_shape beam
cursor_blink_interval 0.5
#background #050505

# ==========================================
# 4. OPTIMIZACIÓN DE RENDIMIENTO (NUEVO)
# ==========================================
# Deshabilitar Input Method Editor
wayland_enable_ime no

# Reducir delays de input/render
input_delay 0
repaint_delay 4
sync_to_monitor yes

# Optimizar rendering
visual_bell_duration 0.0
enable_audio_bell no

# ==========================================
# 4. COLORES DINÁMICOS (WALLUST)
# ==========================================
include /home/dischead/.config/wallust/colores/colors-kitty.conf
