# Plantilla generada por Wallust para Dunst

[urgency_low]
    # El equivalente Hexadecimal a rgba(20, 20, 20, 0.9) es #141414E6
    background = "#141414E6"
    foreground = "{{foreground}}"
    frame_color = "{{color8}}"

[urgency_normal]
    background = "#141414E6"
    foreground = "{{foreground}}"
    # Puedes usar color2 o color1 dependiendo de qué borde prefieras
    frame_color = "{{color2}}" 

[urgency_critical]
    background = "#141414E6"
    foreground = "{{foreground}}"
    # En tu SwayNC usabas @color1 para críticas
    frame_color = "{{color1}}"