general {
    lock_cmd = pidof hyprlock || hyprlock --immediate-render
    before_sleep_cmd = asusctl -k off; pkill -x dunst; pkill -x quickshell; loginctl lock-session
    after_sleep_cmd = asusctl -k high; dunst & sleep 0.5 && quickshell -p ~/.config/quickshell/top-bar/shell.qml &
}

listener {
    timeout = 60
    on-timeout = pidof hyprlock && systemctl suspend
}

listener {
    timeout = 240
    on-timeout = brightnessctl set 20%-
    on-resume = brightnessctl set +10%
}

listener {
    timeout = 300
    on-timeout = loginctl lock-session  # Bloquear primero
}

listener {
    timeout = 330
    on-timeout = asusctl -k off; systemctl suspend
}

listener {
    timeout = 10
    on-timeout = asusctl -k off
    on-resume = asusctl -k high
}
