# =============================================================================
# HYPRLOCK - DISEÑO VERTICAL DINÁMICO (WALLUST)
# =============================================================================
source = /home/dischead/.config/wallust/colores/colors-hypr.conf

general {
    no_fade_in = true
    grace = 0
    disable_loading = true
    hide_cursor = true
    fail_timeout = 0
    fail_transitions = 0
}

# =============================================================================
# FONDO DE PANTALLA
# =============================================================================
background {
    monitor =
    path = $wallpaper
    color = $bg
    blur_passes = 2 
    blur_size = 3
    noise = 0.0117
    contrast = 1.3000
    brightness = 0.6000
    vibrancy = 0.2100
    vibrancy_darkness = 0.0
}

# =============================================================================
# HORA (Gigante Arriba)
# =============================================================================
label {
    monitor =
    text = cmd[update:1000] echo "<b><big> $(date +"%H") </big></b>"
    color = $fg
    font_size = 112
    font_family = JetBrainsMono Nerd Font ExtraBold
    shadow_passes = 1
    shadow_size = 3
    position = 0, 150
    halign = center
    valign = center
}

# =============================================================================
# MINUTOS (Gigante Abajo)
# =============================================================================
label {
    monitor =
    text = cmd[update:1000] echo "<b><big> $(date +"%M") </big></b>"
    color = $color1
    font_size = 112
    font_family = JetBrainsMono Nerd Font ExtraBold
    shadow_passes = 1
    shadow_size = 3
    position = 0, 10
    halign = center
    valign = center
}

# =============================================================================
# DÍA DE LA SEMANA
# =============================================================================
label {
    monitor =
    text = cmd[update:18000000] echo "<b><big> "$(date +'%A')" </big></b>"
    color = $fg
    font_size = 18
    font_family = JetBrainsMono Nerd Font
    position = 0, -100
    halign = center
    valign = center
}

# =============================================================================
# FECHA (Día y Mes)
# =============================================================================
label {
    monitor =
    text = cmd[update:18000000] echo "<b> "$(date +'%d %b')" </b>"
    color = $fg
    font_size = 14
    font_family = JetBrainsMono Nerd Font
    position = 0, -130
    halign = center
    valign = center
}

# =============================================================================
# CAMPO DE CONTRASEÑA
# =============================================================================
input-field {
    monitor =
    size = 250, 50
    outline_thickness = 3
    dots_size = 0.30 
    dots_spacing = 0.64 
    dots_center = true
    dots_rounding = -1
    rounding = 22
    outer_color = $color1
    inner_color = $bg
    font_color = $fg
    check_color = $color2
    fade_on_empty = true
    placeholder_text = <i>wiwiwi</i> 
    position = 0, 50
    halign = center
    valign = bottom
}