# ==========================================
# COLORES DINÁMICOS DE KITTY (WALLUST)
# ==========================================

foreground           #FEFAF3
background           #111111

# Cursor y Selección con tu color de acento
cursor               #F6EFE6
cursor_text_color    #111111
selection_foreground #111111
selection_background #F6EFE6

# Links con tu color secundario
url_color            #355D6A

# --- PALETA DEL SISTEMA ---
color0  #393939
color8  #ACA7A1

color1  #8E9EA2
color9  #8E9EA2

color2  #355D6A
color10 #355D6A

color3  #A78D31
color11 #A78D31

color4  #B98B8E
color12 #B98B8E

color5  #8E9EA2
color13 #8E9EA2

color6  #FDF0DD
color14 #FDF0DD

color7  #F6EFE6
color15 #F6EFE6
