# =========================================================
# VARIABLES GLOBALES PARA HYPRLAND Y HYPRLOCK
# =========================================================

$wallpaper = /home/dischead/Pictures/Wallpapers/nature.png

$bg = rgb(111111)
$fg = rgb(FEFAF3)

$color0 = rgb(393939)
$color1 = rgb(754D43)
$color2 = rgb(355D6A)
$color3 = rgb(A78D31)
$color4 = rgb(B98B8E)
$color5 = rgb(8E9EA2)
$color6 = rgb(FDF0DD)
$color7 = rgb(F6EFE6)
$color8 = rgb(ACA7A1)
$color9 = rgb(754D43)
