# ==========================================
# VARIABLES INYECTADAS POR WALLUST
# ==========================================
$color_active_1 = rgb(DC1B21)
$color_active_2 = rgb(F89122)
$color_inactive = rgb(38393C)

general {
    col.active_border = $color_active_1 $color_active_2 45deg
    col.inactive_border = $color_inactive
}
